name: Publish release

on:
  push:
    branches:
      - release-0.1

jobs:
  call:
    uses: holochain/actions/.github/workflows/publish-release.yml@v1.1.0
    secrets:
      HRA2_GITHUB_TOKEN: ${{ secrets.HRA2_GITHUB_TOKEN }}
      HRA2_CRATES_IO_TOKEN: ${{ secrets.HRA2_CRATES_IO_TOKEN }}
