name: Test

on:
  pull_request: {}

jobs:
  static:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make@0.37.24

      - uses: Swatinem/rust-cache@v2

      # we cannot use cmake 4 until openssl-src is updated
      - name: cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - name: Static
        run: cargo make static

  test:
    needs: static
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Maximize build space (Linux)
        if: runner.os == 'Linux'
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Go Toolchain
        uses: actions/setup-go@v6
        with:
          go-version: '=1.24.6'

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make@0.37.24

      - uses: Swatinem/rust-cache@v2

      # we cannot use cmake 4 until openssl-src is updated
      - name: cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - name: Test
        env:
          RUST_LOG: info
        run: cargo make test

      - name: Examples
        run: cargo run --example schema --features schema

  test-windows:
    needs: static
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Go Toolchain
        uses: actions/setup-go@v6
        with:
          go-version: '=1.24.6'

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make@0.37.24

      - uses: Swatinem/rust-cache@v2

      # we cannot use cmake 4 until openssl-src is updated
      - name: cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'

      - uses: johnwason/vcpkg-action@v7
        with:
          triplet: x64-windows-release
          token: ${{ github.token }}
          manifest-dir: ${{ github.workspace }}/.github/manifest
          github-binarycache: true

      - name: Test
        run: |-
          $env:SODIUM_LIB_DIR="$(pwd)\vcpkg\packages\libsodium_x64-windows-release\lib"
          cargo make test

  nix-build:
    needs: static
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: holochain-wind-tunnel
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build --verbose -L .#bootstrap-srv

  docker-build-bootstrap:
    needs: static
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: docker buildx build -f docker/kitsune2_bootstrap_srv/Dockerfile .

  docker-build-bootstrap-iroh-relay:
    needs: static
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: docker buildx build -f docker/kitsune2_bootstrap_srv_iroh_relay/Dockerfile .

  docker-build-bootstrap-auth-test:
    needs: static
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: docker buildx build -f docker/kitsune2_test_auth_hook_server/Dockerfile .

  changelog-preview-comment:
      name: Add comment of changelog preview
      uses: holochain/actions/.github/workflows/changelog-preview-comment.yml@v1.4.0

  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    needs:
      - static
      - test
      - test-windows
      - nix-build
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
